---
- name: RPi camera taking singular high-res images and pushing to remote backup 
  hosts: camera-push
  remote_user: pi
  debugger: on_failed
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - common
    - rpicam
    - healthchecksio
    - psmqtt
