---
- name: Install apt dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
    update_cache: yes
    state: present
  become: yes

- name: Add python repository
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
  become: yes

- name: Install python3.9
  ansible.builtin.apt:
    name:
      - python3.9
      - python3.9-distutils
      - python3.9-dev
      - python3.9-venv
    update_cache: yes
    state: present
  become: yes
